var OAO=OAO||{};OAO.q=OAO.q||{};OAO.q.c=OAO.q.c||[];
(function(){OAO.q.ias=OAO.q.ias||[];OAO.q.ias.push(["addVisitorData","usePOST",!0]);var e=window.location.hostname||"",m,w,x;m=e.indexOf(".ionos.");w=e.indexOf(".server.lan");x=e.indexOf(".localhost");if(-1===m&&-1===w&&-1===x)return!1;m=e.substr(m+7);if(0===m.indexOf("de"))OAO.q.c.push(["setDefaultMarket","DE"]),OAO.q.c.push(["setDefaultLanguage","de_DE"]),OAO.q.c.push(["setDefaultTenant","IONOS_DE"]);else if(0===m.indexOf("ca"))OAO.q.c.push(["setDefaultMarket","CA"]),OAO.q.c.push(["setDefaultLanguage",
"en_CA"]),OAO.q.c.push(["setDefaultTenant","IONOS_CA"]);else if(0===m.indexOf("es"))OAO.q.c.push(["setDefaultMarket","ES"]),OAO.q.c.push(["setDefaultLanguage","es_ES"]),OAO.q.c.push(["setDefaultTenant","IONOS_ES"]);else if(0===m.indexOf("fr"))OAO.q.c.push(["setDefaultMarket","FR"]),OAO.q.c.push(["setDefaultLanguage","fr_FR"]),OAO.q.c.push(["setDefaultTenant","IONOS_FR"]);else if(0===m.indexOf("it"))OAO.q.c.push(["setDefaultMarket","IT"]),OAO.q.c.push(["setDefaultLanguage","it_IT"]),OAO.q.c.push(["setDefaultTenant",
"IONOS_IT"]);else if(0===m.indexOf("mx"))OAO.q.c.push(["setDefaultMarket","MX"]),OAO.q.c.push(["setDefaultLanguage","es_MX"]),OAO.q.c.push(["setDefaultTenant","IONOS_MX"]);else if(0===m.indexOf("pl"))OAO.q.c.push(["setDefaultMarket","PL"]),OAO.q.c.push(["setDefaultLanguage","pl_PL"]),OAO.q.c.push(["setDefaultTenant","IONOS_PL"]);else if(0===m.indexOf("co.uk")||0===m.indexOf("uk"))OAO.q.c.push(["setDefaultMarket","UK"]),OAO.q.c.push(["setDefaultLanguage","en_GB"]),OAO.q.c.push(["setDefaultTenant",
"IONOS_UK"]);else if(0===m.indexOf("com"))OAO.q.c.push(["setDefaultMarket","US"]),OAO.q.c.push(["setDefaultLanguage","en_US"]),OAO.q.c.push(["setDefaultTenant","IONOS_US"]);else if(-1!==e.indexOf("de.")||-1!==e.indexOf("de-"))OAO.q.c.push(["setDefaultMarket","DE"]),OAO.q.c.push(["setDefaultLanguage","de_DE"]),OAO.q.c.push(["setDefaultTenant","IONOS_DE"]);else if(-1!==e.indexOf("ca.")||-1!==e.indexOf("ca-"))OAO.q.c.push(["setDefaultMarket","CA"]),OAO.q.c.push(["setDefaultLanguage","en_CA"]),OAO.q.c.push(["setDefaultTenant",
"IONOS_CA"]);else if(-1!==e.indexOf("es.")||-1!==e.indexOf("es-"))OAO.q.c.push(["setDefaultMarket","ES"]),OAO.q.c.push(["setDefaultLanguage","es_ES"]),OAO.q.c.push(["setDefaultTenant","IONOS_ES"]);else if(-1!==e.indexOf("fr.")||-1!==e.indexOf("fr-"))OAO.q.c.push(["setDefaultMarket","FR"]),OAO.q.c.push(["setDefaultLanguage","fr_FR"]),OAO.q.c.push(["setDefaultTenant","IONOS_FR"]);else if(-1!==e.indexOf("it.")||-1!==e.indexOf("it-"))OAO.q.c.push(["setDefaultMarket","IT"]),OAO.q.c.push(["setDefaultLanguage",
"it_IT"]),OAO.q.c.push(["setDefaultTenant","IONOS_IT"]);else if(-1!==e.indexOf("mx.")||-1!==e.indexOf("mx-"))OAO.q.c.push(["setDefaultMarket","MX"]),OAO.q.c.push(["setDefaultLanguage","es_MX"]),OAO.q.c.push(["setDefaultTenant","IONOS_MX"]);else if(-1!==e.indexOf("pl.")||-1!==e.indexOf("pl-"))OAO.q.c.push(["setDefaultMarket","PL"]),OAO.q.c.push(["setDefaultLanguage","pl_PL"]),OAO.q.c.push(["setDefaultTenant","IONOS_PL"]);else if(-1!==e.indexOf("uk.")||-1!==e.indexOf("gb.")||-1!==e.indexOf("uk-")||
-1!==e.indexOf("gb-"))OAO.q.c.push(["setDefaultMarket","UK"]),OAO.q.c.push(["setDefaultLanguage","en_GB"]),OAO.q.c.push(["setDefaultTenant","IONOS_UK"]);else if(-1!==e.indexOf("us.")||-1!==e.indexOf("com.")||-1!==e.indexOf("us-")||-1!==e.indexOf("com-"))OAO.q.c.push(["setDefaultMarket","US"]),OAO.q.c.push(["setDefaultLanguage","en_US"]),OAO.q.c.push(["setDefaultTenant","IONOS_US"])})();
(function(){if(window.OAO&&window.OAO.mobile){var e=document.querySelectorAll(".pagemessage[level\x3dinfo], .pagemessage[level\x3dsuccess], .custom-success-message .main-message, .pagemessages-container .subheadline-section, .sheet__section.sheet__section--activating .headline, .sheet__section.sheet__section--success .headline, .sheet__section.sheet__section--warning .headline"),m=document.querySelector(".abort-transaction")||!1;!1!==m&&m.addEventListener?m.addEventListener("click",function(){window.OAO.mobile.abortedAction()}):
!1!==m&&m.attachEvent&&m.attachEvent("onclick",function(){window.OAO.mobile.abortedAction()});e&&0<e.length&&(e=e[0],window.OAO.mobile.finishedAction(e.textContent||e.innerText))}})();(function(){OAO.q.privacyconsent=OAO.q.privacyconsent||[];OAO.q.privacyconsent.push(["addMarketingCallback",function(){OAO.q.t=OAO.q.t||[];OAO.q.t.push(["setUserConsent",!0])}])})();OAO.q.pageintegration=OAO.q.pageintegration||[];OAO.q.notifications=OAO.q.notifications||[];OAO.q.navigation=OAO.q.navigation||[];
OAO.q.navigation.push(["setAppSwitchDisabled",!0]);OAO.q.navigation.push(["hideOffersIcon","always"]);(function(){OAO.q.pageintegration.push(["disableDeeplinkingOnInit"]);OAO.q.pageintegration.push(["setForceShownIFrame"])})();
(function(){OAO.q.notifications.push(["isPushSupported",function(e){if(e&&(e=window.location.hostname||!1,!1!==e)){e=e.replace("login.",".");var m=new Date;m.setTime(m.getTime()+864E5);m="expires\x3d"+m.toUTCString();document.cookie="supportsBrowserPush\x3dtrue;"+m+";domain\x3d"+e+";path\x3d/"}}])})();OAO.q.c.push(["setApplication","CENTRAL_LOGIN"]);OAO.q.c.push(["loadModule","adserver"]);OAO.q.c.push(["loadModule","surveys"]);OAO.q.c.push(["loadModule","statuspage"]);OAO.q.c.push(["loadModule","pushnotifications"]);
OAO.q.c.push(["loadModule","privacy-consent"]);(function(){-1!==(window.location.hostname||"").indexOf(".cpwaterloo")?(OAO.q.navigation.push(["setMode","STAGE"]),OAO.q.c.push(["loadModule","inpagelayer-prelive"]),OAO.q.c.push(["loadModule","globalnavigation-prelive"])):(OAO.q.c.push(["loadModule","inpagelayer"]),OAO.q.c.push(["loadModule","globalnavigation"]))})();
!function(){function e(l){var h=w[l];if(void 0!==h)return h.exports;h=w[l]={exports:{}};return m[l](h,h.exports,e),h.exports}var m={304:function(l){l.exports={Mode:{PROD:"PROD",STAGE:"STAGE",PRELIVE:"PRELIVE",LOCAL:"LOCAL",DEMO:"DEMO",ACI:"ACI"},Market:{CA:"CA",DE:"DE",ES:"ES",FR:"FR",IT:"IT",MX:"MX",PL:"PL",UK:"UK",GB:"UK",US:"US",NL:"NL"},Language:{en_CA:"en_CA",de_DE:"de_DE",es_ES:"es_ES",fr_FR:"fr_FR",it_IT:"it_IT",es_MX:"es_MX",pl_PL:"pl_PL",en_GB:"en_GB",en_US:"en_US",nl_NL:"nl_NL",sv_SE:"sv_SE"},
Tenant:{IONOS:"IONOS_DE",IONOS_DE:"IONOS_DE",IONOS_ES:"IONOS_ES",IONOS_FR:"IONOS_FR",IONOS_IT:"IONOS_IT",IONOS_MX:"IONOS_MX",IONOS_US:"IONOS_US",IONOS_UK:"IONOS_UK",IONOS_GB:"IONOS_UK",IONOS_CA:"IONOS_CA",IONOS_PL:"IONOS_PL",IONOS_CLOUD_DE:"IONOS_CLOUD_DE",IONOS_CLOUD_ES:"IONOS_CLOUD_ES",IONOS_CLOUD_FR:"IONOS_CLOUD_FR",IONOS_CLOUD_IT:"IONOS_CLOUD_IT",IONOS_CLOUD_MX:"IONOS_CLOUD_MX",IONOS_CLOUD_US:"IONOS_CLOUD_US",IONOS_CLOUD_UK:"IONOS_CLOUD_UK",IONOS_CLOUD_GB:"IONOS_CLOUD_UK",IONOS_CLOUD_CA:"IONOS_CLOUD_CA",
STRATO_DE:"STRATO_DE",STRATO_NL:"STRATO_NL",STRATO_ES:"STRATO_ES",STRATO_EA:"STRATO_EA",STRATO_FR:"STRATO_FR",STRATO_IT:"STRATO_IT",STRATO_GB:"STRATO_GB",STRATO_SE:"STRATO_SE",SEDO_DE:"SEDO_DE",SEDO_ES:"SEDO_ES",SEDO_UK:"SEDO_UK",SEDO_FR:"SEDO_FR",SEDO_US:"SEDO_US",ARSYS:"ARSYS",ARSYS_FR:"ARSYS_FR",ARSYS_ES_EN:"ARSYS_ES_EN",FASTHOSTS:"FASTHOSTS",HOME_PL:"HOME_PL",HOME_PL_LEGACY:"HOME_PL_LEGACY",AZ_PL:"AZ_PL",HOMECLOUD_PL:"HOMECLOUD_PL",PIENSA_SOLUTIONS:"PIENSA_SOLUTIONS",UNITED_DOMAINS:"UNITED_DOMAINS",
WORLD4YOU_DE:"WORLD4YOU_DE",WORLD4YOU_US:"WORLD4YOU_US",INTERNETX_DE:"INTERNETX_DE",INTERNETX_US:"INTERNETX_US"},DefaultLanguageForMarket:{CA:"en_CA",DE:"de_DE",ES:"es_ES",FR:"fr_FR",IT:"it_IT",MX:"es_MX",PL:"pl_PL",UK:"en_GB",US:"en_US",NL:"nl_NL"}}},457:function(l,h,b){function k(){return a&&a.performance&&"function"==typeof a.performance.now?a.performance.now():(new Date).getTime()}var f,c,d=b(163),a=b(643),r=(a.document,"UNKNOWN"),g=r,y=r,e=!1,m=!1,t=!1,q=!1,n=!1,v=!1,z=k();l.exports={setClient:function(a){g=
a||r},setClientVersion:function(a){y=a||r},setSentryDsn:function(a){e=a||!1},setSentryProject:function(a){m=a||!1},setSentryEnvironment:function(a){t=a||!1;v&&this.init()},init:function(){if(!1!==e)if(a.Sentry&&a.Sentry.BrowserClient&&window.Sentry.Hub){var b={dsn:e,environment:t||"prod",beforeSend:function(a){return a.extra&&a.extra.oaoClient&&a.extra.oaoClient===g?a:null}};!1!==m&&(b.release=m+"@"+y);b=new a.Sentry.BrowserClient(b);(q=new a.Sentry.Hub).bindClient(b);v=!0;!1!==n&&(this.reportError(n,
f,c),n=!1,f=!1,c=!1)}else b=d.getDefaultHostnameByScriptTag()||"frontend-services.ionos.com/t",d.loadScript("https://"+b+"/sentry/bundle.min.js",function(){this.init()}.bind(this))},reportError:function(b,v,d){if(!1===q)return this.init(),n=b,f=v,void(c=d);q.withScope(function(c){c.setExtra("oaoClient",g);c.setExtra("oaoClientVersion",y);c.setExtra("oaoTimeSinceInit",function(a){if(!a)return!1;var c=k();return!!c&&Math.ceil(c-a)}(z));c.setExtra("oaoUrl",window.location.href||"");v&&c.setExtras(v);
a.OAO.ias.sentryInfo&&(d.iasInfo=JSON.stringify(a.OAO.ias.sentryInfo));d&&c.setTags(d);q.captureException(b)})},getCurrentTime:k}},163:function(l,h,b){var k=b(457),f=b(643).document;l.exports={loadScript:function(c,b){var a,d,g,h=!1;return(d=f.createElement("script")).type="text/javascript",d.async=!0,"function"==typeof b&&(g=function(){if(!(h||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState)){h=!0;try{b()}catch(p){k.reportError(p)}d.onload=null;d.onreadystatechange=null}},
d.onload=g,d.onreadystatechange=g),d.src=c,(a=f.getElementsByTagName("script")[0]).parentNode.insertBefore(d,a),d},getDefaultHostnameByScriptTag:function(){var c;c=document;var d=[];c=c.querySelectorAll&&0<(d=c.querySelectorAll("#oaotag")).length?d[0]:null;if(!c)return!1;d=c.src;if(!d)return!1;d=d.replace("https://","");"//"===(d=d.replace("http://","")).substr(0,2)&&(d=d.substr(2));c=d.indexOf("/tag");return-1!==c&&d.substr(0,c)}}},917:function(l,h,b){var k=b(643).document;l.exports={build:function(b,
c){var d,a,f=encodeURIComponent,g="",h="";if(!(b&&(g+=b.protocol?b.protocol+":":"",a=b.host)))return!1;if("/"===a.substr(-1)&&(a=a.substr(0,a.length-1)),g+=!0===c?a+"/":"//"+a+"/",b.path&&("/"===b.path.substr(0,1)&&(b.path=b.path.substr(1)),g+=b.path),b.query){for(d in b.query)b.query.hasOwnProperty(d)&&(h+=""===h?"?":"\x26",h+=d+"\x3d"+f(b.query[d]));g+=h}return g},getQueryParams:function(b){var c,d,a,f,g={};if(!b&&(c=k.location,!c||!(b=c.search)))return g;if("?"===b.substr(0,1)&&(b=b.substr(1)),
c=b.split("\x26"))for(b=0;b<c.length;b+=1)c[b]&&2===(d=c[b].split("\x3d")).length&&(a=d[0],f=d[1],a&&f&&(g[a]=f));return g},ensureSameProtocol:function(b){var c=k.location.protocol;return!!b&&(0===b.indexOf(c)||("http:"===c?b=b.replace("https://","http://"):"https:"===c&&(b=b.replace("http://","https://"))),b)},isFullQualified:function(b){return!!b&&(0===b.indexOf("http://")||0===b.indexOf("https://"))}}},68:function(l,h,b){var k=b(604),f=b(675),c=b(364),d=b(457);l.exports={init:function(){},setApplication:function(a){k.setApplication(a)},
setPageName:function(a){k.setPageName(a)},setFrontendToken:function(a){f.setFrontendToken(a)},setContractHash:function(a){f.setContractHash(a)},setContract:function(a){f.setContract(a)},setBasketBaseUri:function(a){c.setBasketBaseUri(a)},setShopApiBaseUri:function(a){c.setShopApiBaseUri(a)},setMode:function(a){c.setMode(a)},setHost:function(a){c.setHost(a)},setMarket:function(a){c.setMarket(a)},setDefaultMarket:function(a){c.setDefaultMarket(a)},setLanguage:function(a){c.setLanguage(a)},setDefaultLanguage:function(a){!1===
c.getLanguage()&&c.setLanguage(a)},setTenant:function(a){c.setTenant(a)},setDefaultTenant:function(a){c.setDefaultTenant(a)},loadModule:function(a){try{b(36)("./"+a)}catch(r){d.reportError(r)}},data:{get visitor(){var a={};return f.getFrontendToken()&&(a.frontendToken=f.getFrontendToken()),f.getContractHash()&&(a.contractHash=f.getContractHash()),a},get tracking(){var a={};return k.getApplication()&&(a.application=k.getApplication()),k.getPageName()&&(a.page=k.getPageName()),a},get settings(){var a=
{};return a.isProd=c.isProd(),a.market=c.getMarket(),a.language=c.getLanguage(),a.host=c.getHost(),a.shopApiBaseUri=c.getShopApiBaseUri(),a.basketBaseUri=c.getBasketBaseUri(),a.tenant=c.getTenant(),a}},__version:c.getVersion()}},355:function(l,h,b){function k(){var a=b(643);d.getFrontendToken()&&a.OAO.q.ias.push(["setFrontendSessionToken",d.getFrontendToken()]);d.getContractHash()&&a.OAO.q.ias.push(["setHashContractId",d.getContractHash()]);d.getContract()&&a.OAO.q.ias.push(["addVisitorData","contract",
d.getContract()])}function f(){e.OAO.q.ias.push(["setMode",a.getMode()]);e.OAO.q.ias.push(["setMarket",a.getMarket()]);e.OAO.q.ias.push(["setLanguage",a.getLanguage()]);e.OAO.q.ias.push(["setTenant",a.getTenant()]);a.getShopApiBaseUri()&&e.OAO.q.ias.push(["addVisitorData","shopApiBaseUri",a.getShopApiBaseUri()]);a.getBasketBaseUri()&&e.OAO.q.ias.push(["addVisitorData","basketBaseUri",a.getBasketBaseUri()])}function c(){e.OAO.q.ias.push(["setApplication",r.getApplication()]);e.OAO.q.ias.push(["setPage",
r.getPageName()])}var d=b(675),a=b(364),r=b(604),g=b(681);l=b(378);var e=b(643);e.OAO=e.OAO||{};e.OAO.q=e.OAO.q||{};e.OAO.q.ias=e.OAO.q.ias||[];e.OAO.q.ias.push(["setHost",!1]);d.addChangeListener(k);a.addChangeListener(f);r.addChangeListener(c);k();f();c();l.onQueueFinished(function(){g.loadModule("ias/js/ias","6.13.3")})},954:function(l,h,b){function k(){g.OAO.q.navigation.push(["setFrontendToken",d.getFrontendToken()]);d.getContract()&&g.OAO.q.navigation.push(["setContract",d.getContract()])}
function f(){g.OAO.q.navigation.push(["setMarket",a.getMarket()]);g.OAO.q.navigation.push(["setLanguage",a.getLanguage()]);g.OAO.q.navigation.push(["setTenant",a.getTenant()]);g.OAO.q.navigation.push(["setBasePath",a.getHost()+"/navi-prelive/"])}function c(){g.OAO.q.navigation.push(["setClient",e.getApplication()]);g.OAO.q.navigation.push(["setPageName",e.getPageName()])}var d=b(675),a=b(364),e=b(604);l=b(681);var g=b(643);g.OAO=g.OAO||{};g.OAO.q=g.OAO.q||{};g.OAO.q.navigation=g.OAO.q.navigation||
[];k();f();c();d.addChangeListener(k);a.addChangeListener(f);e.addChangeListener(c);l.loadModule("navi-prelive/js/navigation","6.17.0")},760:function(l,h,b){function k(){g.OAO.q.navigation.push(["setFrontendToken",d.getFrontendToken()]);d.getContract()&&g.OAO.q.navigation.push(["setContract",d.getContract()])}function f(){g.OAO.q.navigation.push(["setMode",a.getMode()]);g.OAO.q.navigation.push(["setMarket",a.getMarket()]);g.OAO.q.navigation.push(["setLanguage",a.getLanguage()]);
g.OAO.q.navigation.push(["setTenant",a.getTenant()]);g.OAO.q.navigation.push(["setBasePath",a.getHost()+"/navi/"]);a.getShopApiBaseUri()&&g.OAO.q.navigation.push(["setShopApiBaseUri",a.getShopApiBaseUri()])}function c(){g.OAO.q.navigation.push(["setClient",e.getApplication()]);g.OAO.q.navigation.push(["setPageName",e.getPageName()])}var d=b(675),a=b(364),e=b(604);l=b(681);var g=b(643);g.OAO=g.OAO||{};g.OAO.q=g.OAO.q||{};g.OAO.q.navigation=g.OAO.q.navigation||[];k();f();c();d.addChangeListener(k);
a.addChangeListener(f);e.addChangeListener(c);l.loadModule("navi/js/navigation","6.17.0")},522:function(l,h,b){function k(){a.OAO.q.pageintegration.push(["setMarket",c.getMarket()]);a.OAO.q.pageintegration.push(["setLanguage",c.getLanguage()]);a.OAO.q.pageintegration.push(["setBasePath",c.getHost()+"/inpagelayer-prelive/"])}function f(){a.OAO.q.pageintegration.push(["setClient",d.getApplication()]);a.OAO.q.pageintegration.push(["setPageName",d.getPageName()])}var c=b(364),d=
b(604);l=b(681);var a=b(643);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.pageintegration=a.OAO.q.pageintegration||[];k();f();c.addChangeListener(k);d.addChangeListener(f);l.loadModule("inpagelayer-prelive/js/inpagelayer","5.2.1")},320:function(l,h,b){function k(){a.OAO.q.pageintegration.push(["setMarket",c.getMarket()]);a.OAO.q.pageintegration.push(["setLanguage",c.getLanguage()]);a.OAO.q.pageintegration.push(["setBasePath",c.getHost()+"/inpagelayer/"])}function f(){a.OAO.q.pageintegration.push(["setClient",
d.getApplication()]);a.OAO.q.pageintegration.push(["setPageName",d.getPageName()])}var c=b(364),d=b(604);l=b(681);var a=b(643);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.pageintegration=a.OAO.q.pageintegration||[];k();f();c.addChangeListener(k);d.addChangeListener(f);l.loadModule("inpagelayer/js/inpagelayer","5.2.1")},152:function(l,h,b){function k(){a.OAO.q.passwordindicator.push(["setMarket",c.getMarket()]);a.OAO.q.passwordindicator.push(["setLanguage",c.getLanguage()]);a.OAO.q.passwordindicator.push(["setBasePath",
c.getHost()+"/password-indicator/"])}function f(){a.OAO.q.passwordindicator.push(["setClient",d.getApplication()]);a.OAO.q.passwordindicator.push(["setPageName",d.getPageName()])}var c=b(364),d=b(604);l=b(681);var a=b(643);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.passwordindicator=a.OAO.q.passwordindicator||[];k();f();c.addChangeListener(k);d.addChangeListener(f);l.loadModule("password-indicator/js/password-indicator","3.2.6")},160:function(l,h,b){function k(){c.OAO.q.privacyconsent.push(["setMarket",
f.getMarket()]);c.OAO.q.privacyconsent.push(["setLanguage",f.getLanguage()])}l=b(681);var f=b(364),c=b(643);c.OAO=c.OAO||{};c.OAO.q=c.OAO.q||{};c.OAO.q.privacyconsent=c.OAO.q.privacyconsent||[];k();f.addChangeListener(k);l.loadModule("privacyconsent-prelive/js/privacyconsent","4.0.1")},54:function(l,h,b){function k(){c.OAO.q.privacyconsent.push(["setMarket",f.getMarket()]);c.OAO.q.privacyconsent.push(["setLanguage",f.getLanguage()])}l=b(681);var f=b(364),c=b(643);c.OAO=
c.OAO||{};c.OAO.q=c.OAO.q||{};c.OAO.q.privacyconsent=c.OAO.q.privacyconsent||[];k();f.addChangeListener(k);l.loadModule("privacyconsent/js/privacyconsent","4.0.1")},545:function(l,h,b){function k(){g.OAO.q.notifications.push(["setFrontendToken",d.getFrontendToken()])}function f(){g.OAO.q.notifications.push(["setMarket",a.getMarket()]);g.OAO.q.notifications.push(["setLanguage",a.getLanguage()]);g.OAO.q.notifications.push(["setBasePath",a.getHost()+"/pushnotifications/"])}function c(){g.OAO.q.notifications.push(["setClient",
e.getApplication()]);g.OAO.q.notifications.push(["setPageName",e.getPageName()])}var d=b(675),a=b(364),e=b(604);l=b(681);var g=b(643);g.OAO=g.OAO||{};g.OAO.q=g.OAO.q||{};g.OAO.q.notifications=g.OAO.q.notifications||[];k();f();c();d.addChangeListener(k);a.addChangeListener(f);e.addChangeListener(c);l.loadModule("pushnotifications/js/pushnotifications","3.0.0")},212:function(l,h,b){function k(){a.OAO.q.statuspage.push(["setMarket",c.getMarket()]);a.OAO.q.statuspage.push(["setLanguage",
c.getLanguage()]);a.OAO.q.statuspage.push(["setBasePath",c.getHost()+"/statuspage/"])}function f(){a.OAO.q.statuspage.push(["setClient",d.getApplication()]);a.OAO.q.statuspage.push(["setPageName",d.getPageName()])}var c=b(364),d=b(604);l=b(681);var a=b(643);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.statuspage=a.OAO.q.statuspage||[];k();f();c.addChangeListener(k);d.addChangeListener(f);l.loadModule("statuspage/js/statuspage","3.1.0")},966:function(l,h,b){function k(){var a=b(643);
d.getFrontendToken()&&a.OAO.q.surveys.push(["setFrontendSessionToken",d.getFrontendToken()]);d.getContract()&&a.OAO.q.surveys.push(["setContract",d.getContract()])}function f(){m.OAO.q.surveys.push(["setMarket",a.getMarket()]);m.OAO.q.surveys.push(["setLanguage",a.getLanguage()]);m.OAO.q.surveys.push(["setTenant",a.getTenant()])}function c(){m.OAO.q.surveys.push(["setClient",e.getApplication()]);m.OAO.q.surveys.push(["setPage",e.getPageName()])}var d=b(675),a=b(364),e=b(604),g=b(681);l=b(378);var m=
b(643);m.OAO=m.OAO||{};m.OAO.q=m.OAO.q||{};m.OAO.q.surveys=m.OAO.q.surveys||[];d.addChangeListener(k);a.addChangeListener(f);e.addChangeListener(c);k();f();c();l.onQueueFinished(function(){g.loadModule("surveys/js/surveys","2.1.0")})},300:function(e,h,b){function k(){g.OAO.q.t.push(["setFrontendToken",d.getFrontendToken()])}function f(){g.OAO.q.t.push(["setMode",a.getMode()]);g.OAO.q.t.push(["setMarket",a.getMarket()]);g.OAO.q.t.push(["setTenant",a.getTenant()])}function c(){g.OAO.q.t.push(["setApplication",
l.getApplication()]);g.OAO.q.t.push(["setPage",l.getPageName()])}var d=b(675),a=b(364),l=b(604);e=b(681);var g=b(643);g.OAO=g.OAO||{};g.OAO.q=g.OAO.q||{};g.OAO.q.t=g.OAO.q.t||[];k();f();c();d.addChangeListener(k);a.addChangeListener(f);l.addChangeListener(c);e.loadModule("t/js/t","2.5.0")},455:function(e,h,b){function k(){a.OAO.q.tour.push(["setMarket",c.getMarket()]);a.OAO.q.tour.push(["setLanguage",c.getLanguage()]);a.OAO.q.tour.push(["setBasePath",c.getHost()+"/welcometour/"])}function f(){a.OAO.q.tour.push(["setClient",
d.getApplication()]);a.OAO.q.tour.push(["setPageName",d.getPageName()])}var c=b(364),d=b(604);e=b(681);var a=b(643);a.OAO=a.OAO||{};a.OAO.q=a.OAO.q||{};a.OAO.q.tour=a.OAO.q.tour||[];k();f();c.addChangeListener(k);d.addChangeListener(f);e.loadModule("welcometour/js/welcome-tour","3.0.1")},364:function(e,h,b){var k;h=b(304);var f=h.Market,c=h.Language,d=h.Tenant,a=h.Mode;h=b(228);b=b(7).EventEmitter;var l=a.PROD,g=!1,m=f.DE,p=!1,u=d.IONOS_DE,t=!1,q=!1,n=!1;b=h({},b.prototype,{emitChange:function(){this.emit("change")},
addChangeListener:function(a){this.on("change",a)},getVersion:function(){return"1.0.0"},isProd:function(){return l===a.PROD},getMode:function(){return l},setMode:function(b){b?(b=b.toUpperCase(),a[b]||(b=a.PROD)):b=a.PROD;var c=l!==b;l=b;c&&this.emitChange()},getMarket:function(){return g||m},setMarket:function(a){a?("GB"===(a=a.toUpperCase())&&(a=f.UK),f[a]||(a=f.DE)):a=f.DE;var b=g!==a;g=a;b&&this.emitChange()},setDefaultMarket:function(a){a?("GB"===(a=a.toUpperCase())&&(a=f.UK),f[a]||(a=f.DE)):
a=f.DE;var b=m!==a;m=a;b&&this.emitChange()},getLanguage:function(){return p},setLanguage:function(a){if(a&&-1!==a.indexOf("_")){var b,d,f=a.indexOf("_");(b=a.substr(0,f)||"",d=a.substr(f+1)||"",b=b.toLowerCase(),d=d.toUpperCase(),c[a=b+"_"+d])?(b=p!==a,p=a,b&&this.emitChange()):p=!1}else p=!1},getTenant:function(){return t||u},setTenant:function(a){a?(a=a.toUpperCase(),d[a]||(a=d.IONOS_DE)):a=d.IONOS_DE;var b=t!==a;t=a;b&&this.emitChange()},setShopApiBaseUri:function(a){var b=q!==a;q=a||!1;b&&this.emitChange()},
getShopApiBaseUri:function(){return q},setBasketBaseUri:function(a){var b=n!==a;n=a||!1;b&&this.emitChange()},getBasketBaseUri:function(){return n},setDefaultTenant:function(a){a?(a=a.toUpperCase(),d[a]||(a=d.IONOS_DE)):a=d.IONOS_DE;var b=u!==a;u=a;b&&this.emitChange()},getHost:function(){return k},setHost:function(a){var b=k!==a;k=a||!1;b&&this.emitChange()}});e.exports=b},604:function(e,h,b){h=b(228);b=b(7).EventEmitter;var k=!1,f=!1;b=h({},b.prototype,{emitChange:function(){this.emit("change")},
addChangeListener:function(b){this.on("change",b)},getApplication:function(){return k},setApplication:function(b){var c=k!==b;k=b||!1;c&&this.emitChange()},getPageName:function(){return f},setPageName:function(b){if(b){try{b=(b=(b=(b=b.replaceAll(/^\s+|\s+$/g,"")).replaceAll(/\s\s+/g," ")).replaceAll(" ","-")).replaceAll(/#(.*)/g,"")}catch(a){b=(b=(b=(b=b.replace(/^\s+|\s+$/g,"")).replace(/\s\s+/g," ")).replace(" ","-")).replace(/#(.*)/g,"")}b=b.replace(/;jsessionid=([A-Za-z0-9.]+)/,"")}var d=f!==
b;f=b||!1;d&&this.emitChange()}});e.exports=b},675:function(e,h,b){h=b(228);b=b(7).EventEmitter;var k=!1,f=!1,c=!1;b=h({},b.prototype,{emitChange:function(){this.emit("change")},addChangeListener:function(b){this.on("change",b)},getFrontendToken:function(){return k},setFrontendToken:function(b){var a=k!==b;k=b||!1;a&&this.emitChange()},getContractHash:function(){return f},getContract:function(){return c},setContractHash:function(b){var a=f!==b;f=b||!1;a&&this.emitChange()},setContract:function(b){var a=
c!==b;c=b||!1;a&&this.emitChange()}});e.exports=b},741:function(e,h,b){var k=b(163);h=b(364);b=b(604);(k=k.getDefaultHostnameByScriptTag())&&h.setHost(k);(h=function(){var b=window.location;if(!b||!b.pathname)return!1;for(var b=b.pathname.split("/"),c=0;c<b.length;c+=1)if(b[c]&&""!==b[c]){var d=b[c].split("#",2)[0].split("\\?",2)[0].split(";",2)[0];if(d&&""!==d)return d}return"HOME"}())&&b.setPageName(h);e.exports={}},378:function(e,h,b){h=b(7).EventEmitter;var k=b(228);b=b(643);b.OAO=b.OAO||{};b.OAO.q=
b.OAO.q||{};var f=b.OAO.q.c||[],c=!1,d=k({},h.prototype,{addPushListener:function(a){this.on("push",a)},removePushListener:function(a){this.removeListener("push",a)},onQueueFinished:function(a){c?window.setTimeout(a,0):this.on("ready",a)},push:function(){if(!(1>arguments.length)){var a=0>=arguments.length?void 0:arguments[0];if(a&&a.length&&!(1>a.length)){var b=a[0],a=a.slice(1);this.emit("push",b,a)}}},process:function(){for(var a=0;a<f.length;a+=1){var b=[];b.push(f[a]);d.push.apply(d,b)}f=[];c=
!0;this.emit("ready")}});b.OAO.q.c={push:function(){for(var a=arguments.length,b=Array(a),c=0;c<a;c++)b[c]=arguments[c];d.push.apply(d,b)}};e.exports=d},681:function(e,h,b){var k=b(364),f=b(163),c=b(917);e.exports={loadScript:f.loadScript,loadModule:function(b,a,e){b={host:k.getHost(),path:b+".js",query:{v:a||1}};k.isProd()&&(b.protocol="https");f.loadScript(c.build(b),e)}}},635:function(e,h,b){var k=b(378),f=b(68),c=b(457);c.setClient("TAG_MANAGER");c.setClientVersion("1.0.0");c.setSentryDsn("https://236c7da13ef44014830813657f2e5fb7@sentry.ionos.com/25");
c.setSentryProject("tagmanager-fi");c.init();h=function(){k.addPushListener(function(b,a){b&&(a=a||[],"function"==typeof f[b]&&f[b].apply(f,a))});try{b(741),k.process(),f.init()}catch(d){c.reportError(d)}return f}();e.exports=h},7:function(e){function h(){h.init.call(this)}function b(a){if("function"!=typeof a)throw new TypeError('The "listener" argument must be of type Function. Received type '+typeof a);}function k(a,c,d,f){var e,n,g;if(b(d),void 0===(n=a._events)?(n=a._events=Object.create(null),
a._eventsCount=0):(void 0!==n.newListener&&(a.emit("newListener",c,d.listener?d.listener:d),n=a._events),g=n[c]),void 0===g)n[c]=d,++a._eventsCount;else if("function"==typeof g?g=n[c]=f?[d,g]:[g,d]:f?g.unshift(d):g.push(d),0<(e=void 0===a._maxListeners?h.defaultMaxListeners:a._maxListeners)&&g.length>e&&!g.warned)g.warned=!0,d=Error("Possible EventEmitter memory leak detected. "+g.length+" "+String(c)+" listeners added. Use emitter.setMaxListeners() to increase limit"),d.name="MaxListenersExceededWarning",
d.emitter=a,d.type=c,d.count=g.length,console&&console.warn&&console.warn(d);return a}function f(){if(!this.fired)return this.target.removeListener(this.type,this.wrapFn),this.fired=!0,0===arguments.length?this.listener.call(this.target):this.listener.apply(this.target,arguments)}function c(a,b,c){a={fired:!1,wrapFn:void 0,target:a,type:b,listener:c};b=f.bind(a);return b.listener=c,a.wrapFn=b,b}function d(a,b,c){a=a._events;if(void 0===a)return[];b=a[b];if(void 0===b)c=[];else if("function"==typeof b)c=
c?[b.listener||b]:[b];else if(c)for(c=Array(b.length),a=0;a<c.length;++a)c[a]=b[a].listener||b[a];else c=l(b,b.length);return c}function a(a){var b=this._events;if(void 0!==b){a=b[a];if("function"==typeof a)return 1;if(void 0!==a)return a.length}return 0}function l(a,b){for(var c=Array(b),d=0;d<b;++d)c[d]=a[d];return c}function g(a,b,c,d){if("function"==typeof a.on)d.once?a.once(b,c):a.on(b,c);else{if("function"!=typeof a.addEventListener)throw new TypeError('The "emitter" argument must be of type EventEmitter. Received type '+
typeof a);a.addEventListener(b,function A(f){d.once&&a.removeEventListener(b,A);c(f)})}}var m,p="object"==typeof Reflect?Reflect:null,u=p&&"function"==typeof p.apply?p.apply:function(a,b,c){return Function.prototype.apply.call(a,b,c)};m=p&&"function"==typeof p.ownKeys?p.ownKeys:Object.getOwnPropertySymbols?function(a){return Object.getOwnPropertyNames(a).concat(Object.getOwnPropertySymbols(a))}:function(a){return Object.getOwnPropertyNames(a)};var t=Number.isNaN||function(a){return a!=a};e.exports=
h;e.exports.once=function(a,b){return new Promise(function(c,d){function f(c){a.removeListener(b,e);d(c)}function e(){"function"==typeof a.removeListener&&a.removeListener("error",f);c([].slice.call(arguments))}g(a,b,e,{once:!0});"error"!==b&&function(a,b,c){"function"==typeof a.on&&g(a,"error",b,c)}(a,f,{once:!0})})};h.EventEmitter=h;h.prototype._events=void 0;h.prototype._eventsCount=0;h.prototype._maxListeners=void 0;var q=10;Object.defineProperty(h,"defaultMaxListeners",{enumerable:!0,get:function(){return q},
set:function(a){if("number"!=typeof a||0>a||t(a))throw new RangeError('The value of "defaultMaxListeners" is out of range. It must be a non-negative number. Received '+a+".");q=a}});h.init=function(){void 0!==this._events&&this._events!==Object.getPrototypeOf(this)._events||(this._events=Object.create(null),this._eventsCount=0);this._maxListeners=this._maxListeners||void 0};h.prototype.setMaxListeners=function(a){if("number"!=typeof a||0>a||t(a))throw new RangeError('The value of "n" is out of range. It must be a non-negative number. Received '+
a+".");return this._maxListeners=a,this};h.prototype.getMaxListeners=function(){return void 0===this._maxListeners?h.defaultMaxListeners:this._maxListeners};h.prototype.emit=function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(arguments[c]);var c="error"===a,d=this._events;if(void 0!==d)c=c&&void 0===d.error;else if(!c)return!1;if(c){var f;if(0<b.length&&(f=b[0]),f instanceof Error)throw f;b=Error("Unhandled error."+(f?" ("+f.message+")":""));throw b.context=f,b;}c=d[a];if(void 0===c)return!1;
if("function"==typeof c)u(c,this,b);else for(f=c.length,d=l(c,f),c=0;c<f;++c)u(d[c],this,b);return!0};h.prototype.addListener=function(a,b){return k(this,a,b,!1)};h.prototype.on=h.prototype.addListener;h.prototype.prependListener=function(a,b){return k(this,a,b,!0)};h.prototype.once=function(a,d){return b(d),this.on(a,c(this,a,d)),this};h.prototype.prependOnceListener=function(a,d){return b(d),this.prependListener(a,c(this,a,d)),this};h.prototype.removeListener=function(a,c){var d,f,e,g,h;if((b(c),
void 0===(f=this._events))||void 0===(d=f[a]))return this;if(d===c||d.listener===c)0===--this._eventsCount?this._events=Object.create(null):(delete f[a],f.removeListener&&this.emit("removeListener",a,d.listener||c));else if("function"!=typeof d){e=-1;for(g=d.length-1;0<=g;g--)if(d[g]===c||d[g].listener===c){h=d[g].listener;e=g;break}if(0>e)return this;if(0===e)d.shift();else{for(;e+1<d.length;e++)d[e]=d[e+1];d.pop()}1===d.length&&(f[a]=d[0]);void 0!==f.removeListener&&this.emit("removeListener",a,
h||c)}return this};h.prototype.off=h.prototype.removeListener;h.prototype.removeAllListeners=function(a){var b,c;if(void 0===(c=this._events))return this;if(void 0===c.removeListener)return 0===arguments.length?(this._events=Object.create(null),this._eventsCount=0):void 0!==c[a]&&(0===--this._eventsCount?this._events=Object.create(null):delete c[a]),this;if(0===arguments.length){var d=Object.keys(c);for(c=0;c<d.length;++c)"removeListener"!==(b=d[c])&&this.removeAllListeners(b);return this.removeAllListeners("removeListener"),
this._events=Object.create(null),this._eventsCount=0,this}if("function"==typeof(b=c[a]))this.removeListener(a,b);else if(void 0!==b)for(c=b.length-1;0<=c;c--)this.removeListener(a,b[c]);return this};h.prototype.listeners=function(a){return d(this,a,!0)};h.prototype.rawListeners=function(a){return d(this,a,!1)};h.listenerCount=function(b,c){return"function"==typeof b.listenerCount?b.listenerCount(c):a.call(b,c)};h.prototype.listenerCount=a;h.prototype.eventNames=function(){return 0<this._eventsCount?
m(this._events):[]}},228:function(e){var h=Object.getOwnPropertySymbols,b=Object.prototype.hasOwnProperty,k=Object.prototype.propertyIsEnumerable;e.exports=function(){try{if(!Object.assign)return!1;var b=new String("abc");if(b[5]="de","5"===Object.getOwnPropertyNames(b)[0])return!1;for(var c={},b=0;10>b;b++)c["_"+String.fromCharCode(b)]=b;if("0123456789"!==Object.getOwnPropertyNames(c).map(function(a){return c[a]}).join(""))return!1;var d={};return"abcdefghijklmnopqrst".split("").forEach(function(a){d[a]=
a}),"abcdefghijklmnopqrst"===Object.keys(Object.assign({},d)).join("")}catch(a){return!1}}()?Object.assign:function(f,c){var d,a,e;if(null==f)throw new TypeError("Object.assign cannot be called with null or undefined");e=Object(f);for(var g=1;g<arguments.length;g++){for(var l in d=Object(arguments[g]))b.call(d,l)&&(e[l]=d[l]);if(h){a=h(d);for(var m=0;m<a.length;m++)k.call(d,a[m])&&(e[a[m]]=d[a[m]])}}return e}},36:function(e,h,b){function k(c){c=f(c);return b(c)}function f(d){if(!b.o(c,d))throw d=
Error("Cannot find module '"+d+"'"),d.code="MODULE_NOT_FOUND",d;return c[d]}var c={"./adserver":355,"./adserver.js":355,"./globalnavigation":760,"./globalnavigation-prelive":954,"./globalnavigation-prelive.js":954,"./globalnavigation.js":760,"./inpagelayer":320,"./inpagelayer-prelive":522,"./inpagelayer-prelive.js":522,"./inpagelayer.js":320,"./password-indicator":152,"./password-indicator.js":152,"./privacy-consent":54,"./privacy-consent-prelive":160,"./privacy-consent-prelive.js":160,"./privacy-consent.js":54,
"./pushnotifications":545,"./pushnotifications.js":545,"./statuspage":212,"./statuspage.js":212,"./surveys":966,"./surveys.js":966,"./tracking":300,"./tracking.js":300,"./welcometour":455,"./welcometour.js":455};k.keys=function(){return Object.keys(c)};k.resolve=f;e.exports=k;k.id=36},643:function(e){e.exports=window}},w={};e.o=function(e,h){return Object.prototype.hasOwnProperty.call(e,h)};var x=e(635);(OAO=void 0===OAO?{}:OAO).c=x}();